core/urls.py
from django.urls import path, include
<<<<<<< HEAD
from .views import IndexView, page_not_found, server_error
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("500/", server_error, name="server_error"),
    path("404/", page_not_found, name="page_not_found"),
=======

from .views import IndexView
from core.views import pagina_nao_encontrada, erro_servidor

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
<<<<<<< HEAD
>>>>>>> a8c0174 (include core app and configs)
=======
    path("404/", pagina_nao_encontrada, name="pagina_nao_encontrada"),
    path("500/", erro_servidor, name="erro_servidor")
>>>>>>> d3380e7 (add corrections)
]

# paginas e Erro
handler404 = 'core.views.pagina_nao_encontrada'
handler500 = 'core.views.erro_servidor'

pi1tg18/urls.py
from django.contrib import admin
<<<<<<< HEAD
from django.urls import path
=======
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
<<<<<<< HEAD
<<<<<<< HEAD
from django.views.generic import TemplateView

>>>>>>> 86a1e24 (preparing static file folder and template with html test)
=======
from schedule.views import all_events
>>>>>>> a8c0174 (include core app and configs)
=======
from schedule.views import all_events
>>>>>>> 16093fb (created app schedule, config and tests)

urlpatterns = [
    path("", include('core.urls')),
    path('accounts/', include('allauth.urls')),
    path("schedule/", include('schedule.urls')),
    path("school/", include('school.urls')),
    path("teacher/", include('teacher.urls')),
    path("student/", include('student.urls')),
    path("discipline/", include('discipline.urls')),
    path("group/", include('group.urls')),
    path('admin/', admin.site.urls),
    path("all_events/", all_events, name="all_events"),

]
<<<<<<< HEAD
=======

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns


# paginas e Erro
handler404 = 'core.views.pagina_nao_encontrada'
handler500 = 'core.views.erro_servidor'
>>>>>>> d3380e7 (add corrections)

teacher/urls.py
<<<<<<< HEAD
from django.urls import path, include

from .views import TeacherGroupView, TeacherListView, TeacherCreateView

urlpatterns = [   
    path("", TeacherListView.as_view(), name="teacher_all"),
    path("new/", TeacherCreateView.as_view(), name="teacher_new"),
    path("<int:pk>/detail/", TeacherGroupView.as_view(), name="teacher_detail"),
=======
from .views import TeacherCreateView, TeacherDeleteView, TeacherDetailView, TeacherUpdateView, TeacherListView
from django.urls import path


urlpatterns = [
    path("", TeacherListView.as_view(), name="teacher_all"),
    path('<int:pk>/detail', TeacherDetailView.as_view(), name='teacher_detail'),
    path('new/', TeacherCreateView.as_view(), name='teacher_create'),
    path('<int:pk>/update/', TeacherUpdateView.as_view(), name='teacher_update'),
    path('<int:pk>/delete/', TeacherDeleteView.as_view(), name='teacher_delete'),
>>>>>>> ee2e9db (add, configurate and edit app teacher)
]

group/models.py
<<<<<<< HEAD
from typing import Iterable
from django.db import models
from django.utils.translation import gettext_lazy as _
from datetime import datetime, timedelta
from django.urls import reverse

from school.models import School, ClassRoom, TurnSchool, SchoolYear
from teacher.models import Teacher
from graduation.models import Graduation, Discipline


class GroupId_Choice(models.TextChoices):
    A = 'A', _('A')
    B = 'B', _('B')
    C = 'C', _('C')
    D = 'D', _('D')
    E = 'E', _('E')
    F = 'F', _('F')
    G = 'G', _('G')


class DayWeek_Choice(models.TextChoices):
    SUNDAY = 'sunday', _('Domingo')
    MONDAY = 'monday', _('Segunda-Feira')
    TUESDAY = 'tuesday', _("Terca-Feira")
    WEDNESDAY = 'wednesday', _('Quarta-Feira')
    THURSDAY = 'thursday', _('Quinta-Feira')
    FRIDAY = 'friday', _('Sexta-Feira')
    SATURDAY = 'saturday', _('Sábado')

class Discipline_Choice(models.TextChoices):
    MATH = 'math', _('Matemática')
    HISTORY = 'history', _('História')
    GEOGRAPHY = 'geography', _('Geografia')
    SCIENCE = 'science', _('Ciência')
    ART = 'art', _('Artes')
    ENGLISH = 'english', _('Inglês')
    SPANISH = 'spanish', _('Espanhol')
    FRENCH = 'french', _('Francês')
    DRAMATICS = 'dramatics', _('Dramartugia')
    PHYSCIALEDucATION = 'physicaleducation', _('Educação Física')
    WOODSHOP = 'woodshop', _('Marcenaria')
    HEALTH = 'health', _('Saúde')
    ECONOMICS = 'economics', _('Econômia')


class Group(models.Model):
    classroom = models.ForeignKey(
        ClassRoom, 
        verbose_name=_("Sala de Aula"), 
        on_delete=models.CASCADE,
    )
    graduation = models.ForeignKey(
        Graduation, 
        verbose_name=_("Graduação"), 
        on_delete=models.CASCADE,
    )
    group_id = models.CharField(_("Identificador"), max_length=1, choices=GroupId_Choice.choices, default='A')
    school_year = models.ForeignKey(
        SchoolYear, 
        verbose_name=_("Ano Letivo"), 
        on_delete=models.CASCADE
    )
    turn = models.ForeignKey(
        TurnSchool, 
        verbose_name=_("Turno"), 
        on_delete=models.CASCADE
    )
    interval_start = models.TimeField(_("Inicio do intervalo"), null=True, blank=True)
    interval_duration = models.PositiveIntegerField(_("Duração do Intervalo"), null=True, blank=True)

    class Meta:
        verbose_name = _("Classe")
        verbose_name_plural = _("Classes")

    def __str__(self):
        return f'{self.graduation} {self.group_id}'
    
    @property
    def get_start(self):
        start = self.interval_start.strftime('%H%M')
        return start

    @property
    def get_interval_end(self):
        data = datetime.now()
        start = datetime(year=data.year, month=data.month, day=data.day, hour=self.interval_start.hour, minute=self.interval_start.minute)
        end = self.interval_duration
        end_time = start + timedelta(minutes=end)
        print(end_time)
        return end_time.strftime("%H%M")

    @property
    def get_duration_interval(self):
        return f'{self.interval_duration / 60 } h'

class GridGroup(models.Model):

    group = models.ForeignKey(
        Group, 
        verbose_name=_("Classe"), 
        on_delete=models.CASCADE
    )
    day_week = models.CharField(_("Dia da Semana"), max_length=15, choices=DayWeek_Choice.choices)
    time_start = models.TimeField(_("Horario inicial"))
    duration_lesson = models.PositiveIntegerField(_("Duração (minutos)"), default=60, help_text='Informe um intervalo em minutos')
    dicipline = models.CharField(_("Diciplina"), max_length=20, choices=Discipline_Choice.choices, null=True, blank=True)
    teacher = models.ForeignKey(
        Teacher, 
        verbose_name=_("Professor"), 
        on_delete=models.CASCADE
    )
    description = models.CharField(_("Descrição"), max_length=254)
    @property
    def get_start(self):
        start = self.time_start.strftime('%H%M')
        return start
    
    @property
    def get_end_lesson(self):
        data = datetime.now()
        start = datetime(year=data.year, month=data.month, day=data.day, hour=self.time_start.hour, minute=self.time_start.minute)
        end = self.duration_lesson
        end_time = start + timedelta(minutes=end)
        
        return end_time.strftime("%H%M")
    
    @property
    def get_duration_time(self):
        return f'{self.duration_lesson / 60 } h'
    
    class Meta:
        verbose_name = _("GripGroup")
        verbose_name_plural = _("GripGroups")

    def __str__(self):
        return f''

    def get_absolute_url(self):
        return reverse("gridgroup_detail", kwargs={"pk": self.pk})
    
=======
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.db.models import Q


from core.models import TimeStamp
from student.models import Student
from discipline.models import Graduation
from school.models import School, StructSchool
from teacher.models import Teacher


class IdentificationGroupChoice(models.TextChoices):
    A = 'A',
    B = 'B',
    c = 'C',
    D = 'D',
    E = 'E',
    F = 'F',
    G = 'G',
    H = 'H',
    I = 'I',
    J = 'J',
    K = 'K',
    L = 'L',
    M = 'M',
    N = 'N',
    O = 'O',

class TurnChoice(models.TextChoices):
    MANHA = 'M',_('Manhã')
    TARDE = 'T', _('Tarde')
    NOITE = 'N', _('Noite')

class Group(TimeStamp):

    identification_group = models.CharField(_("Nome"),
                                            max_length=1,
                                            choices=IdentificationGroupChoice.choices,
                                            )

    turn = models.CharField(_("Turno"), max_length=1, choices=TurnChoice.choices, blank=True, null=True)

    school = models.ForeignKey(
        School,
        verbose_name=_("Escola"),
        on_delete=models.CASCADE,
    )

    graduation = models.ForeignKey(
        Graduation,
        verbose_name=_("Graduação"),
        on_delete=models.CASCADE,
    )

    localization = models.ForeignKey(
        StructSchool,
        verbose_name=_("Localização"),
        on_delete=models.CASCADE,
    )

    teacher_manager = models.ForeignKey(
        Teacher,
        verbose_name=_("Professor Responável"),
        on_delete=models.CASCADE,
    )

    students = models.ManyToManyField(
        Student,
        verbose_name=_("Estudantes"))

    class Meta:

        verbose_name = 'Classe'
        verbose_name_plural = 'Classes'

    def name(self):

        return f'{self.graduation}-{self.name} '

    @property
    def get_information(self):
        result = Group.objects.values().annotate(
            matriculados=models.Count('students', filter=Q(id=self.id))
        )
        return result

    @property
    def get_vagas(self):
        result = self.localization.vagas - self.get_matriculados
        return result

    @ property
    def get_matriculados(self):
        query = self.get_information
        for alunos in query:
            if alunos['id'] == self.id:
                return alunos['matriculados']

    def __str__(self):

        return f'{self.graduation} - {self.name}'

    def get_fields(self):

        return [(field.verbose_name, field.value_from_object(self))
                for field in self.__class__._meta.fields[1:]
                ]

    def save_model(self, request, obj, form, change):
        if not change:
            for student in self.students.all():
                if not student.registered:
                    student.matricular()

            obj.user = request.user
            obj.save()
        super(Group, self).save_model(request, obj, form, change)
>>>>>>> 93b9589 (add and config new app group)

teacher/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
<<<<<<< HEAD
from django.urls import reverse

from core.models import City, Address, PhoneBase
from school.models import School

class Teacher(models.Model):

    first_name = models.CharField(_("Nome"), max_length=20)
    last_name = models.CharField(_("Sobrenome"), max_length=70)
    email = models.EmailField(_("E-mail"), max_length=254)
    school = models.ForeignKey(
        School, 
        verbose_name=_("Escola"), 
        on_delete=models.PROTECT,
    )

    @property
    def full_name(self):
        return f'{self.first_name.title()} {self.last_name.title()}'
    
    class Meta:
        verbose_name = _("Professor(a)")
        verbose_name_plural = _("Professores")

    def __str__(self):
        return self.full_name
    
    def get_absolute_url(self):
        
        return reverse('teacher_detail', kwargs={'pk': self.pk})

class AddressTeacher(models.Model):

    zipcode = models.OneToOneField(
        Address, 
        verbose_name=_("CEP"),
        on_delete=models.PROTECT
    )
    number = models.PositiveIntegerField(_("Número"))
    complement = models.CharField(_("Complemento"), max_length=20, null=True, blank=True)
    teacher = models.ForeignKey(
        Teacher, 
        verbose_name=_("Professor"),
        on_delete=models.CASCADE,
    )
    
    class Meta:
        verbose_name = _("Endereço do Professor(a)")
        verbose_name_plural = _("Endereços do Professor(a)")

    def __str__(self):
        return self.zipcode.get_address()

class PhoneTeacher(PhoneBase):

    CELULAR = 'C'
    PRINCIPAL = 'P'
    WHATSAPP = 'W'
    TELEGRAN = 'T'
    OUTRO = 'O'
    PHONE_TYPE_CHOICES = {
        CELULAR: 'Celular',
        PRINCIPAL: 'Principal',
        WHATSAPP: 'Whatsapp',
        TELEGRAN: 'Telegran',
        OUTRO: 'Outro',
    }
    teacher = models.ForeignKey(
        Teacher, 
        verbose_name=_("Professor"),
        on_delete=models.CASCADE)
    phone_type = models.CharField(
        max_length=1,
        choices=PHONE_TYPE_CHOICES,
        default=PRINCIPAL,
    )

    @property
    def get_phone(self):
        prefix = ''
        if self.country_code:
            prefix = f'+{self.country_code}'
        if self.locale_code:
            prefix += f'({self.locale_code})'
        
        return f'{prefix} {self.number}'
    
    def is_upperclass(self):
        return self.phone_type in {self.CELULAR, self.PRINCIPAL}

    class Meta:
        verbose_name = _("Telefone do Professor(a)")
        verbose_name_plural = _("Telefones do Professor(a)")

    def __str__(self):
        return f'+{self.country_code}({self.locale_code}) {self.number}'
=======

from core.models import TimeStamp
from school.models import School


class Teacher(TimeStamp):

    school = models.ForeignKey(
        School,
        verbose_name=_("Escola"),
        on_delete=models.DO_NOTHING)

    first_name = models.CharField(_("Primeiro Nome"), max_length=50)
    last_name = models.CharField(_("Sobrenome"), max_length=70)

    email = models.EmailField(_("E-mail"), max_length=254)

    phone_ddd = models.CharField(_("DDD"), max_length=4)
    phone_number = models.CharField(_("Telefone"), max_length=9)

    address_zipcode = models.CharField(_("CEP"), max_length=9)
    address = models.CharField(_("Endereço"), max_length=150)
    address_number = models.CharField(_("Número"), max_length=5)
    address_complement = models.CharField(_("Complemento"), max_length=20)
    address_district = models.CharField(_("Bairro"), max_length=50)
    address_city = models.CharField(_("Cidade"), max_length=70)
    address_state = models.CharField(_("UF"), max_length=2)

    class Meta:
        """Meta definition for Teacher."""

        verbose_name = 'Professor'
        verbose_name_plural = 'Professores'

    def full_name(self):
        return f'{self.first_name.upper()} {self.last_name.upper()}'

    def __str__(self):
        """Unicode representation of Teacher."""
        return self.first_name

    def get_fields(self):
        return [(field.verbose_name, field.value_from_object(self))
                for field in self.__class__._meta.fields[1:]
                ]
>>>>>>> ee2e9db (add, configurate and edit app teacher)

teacher/forms.py
from django.http import request
from django import forms
<<<<<<< HEAD
=======
from django.utils.translation import gettext_lazy as _
>>>>>>> ee2e9db (add, configurate and edit app teacher)

from .models import Teacher


class TeacherForm(forms.ModelForm):
<<<<<<< HEAD
    
    class Meta:
        model = Teacher
        fields = '__all__'
    
    
=======

    class Meta:
        model = Teacher
<<<<<<< HEAD
        fields = '__all__'
>>>>>>> ee2e9db (add, configurate and edit app teacher)
=======
        fields = ['school', 'first_name', 'last_name', 'email', 'phone_ddd', 'phone_number', 'address_zipcode',
                  'address', 'address_number', 'address_complement', 'address_district', 'address_city', 'address_state']
>>>>>>> 8b7b00c (corrections in apps views, forms and templates)

teacher/templates/teacher/teacher_form.html
{% extends "base.html" %}

{% load static humanize %}

{% block content %}

<<<<<<< HEAD
    <div class="container-fluid home-index p-5">
        <div class="container text-center">         
            <div class="container" id='wrap'>
                <div class="container d-flex justify-self-center mt-5 pb-3">
                    <div class="table-responsive col mt-5">
                        <h1 class="text-center">Cadastro do Professor</h1>
                        <form action="" method="post">
                            {% csrf_token %}
                            <table class="table">
                                <tbody>
                                    <tr>
                                        {{ form.as_table }}
                                    </tr> 
                                </tbody>
                            </table>
                            <div class="container d-flex justify-content-center">
                                <input type="submit" class="btn btn-primary btn-lg" value="Salvar">
                                <input type="submit" class="btn btn-danger btn-lg" onclick="window.location='{% url 'teacher_all' %}'; return false;" value="Cancelar">
                            </div>    
                        </form> 

                    </div>
                </div>
            </div>
        </div>
    </div>
=======
    {% include 'parciais/_navbar.html' %}
    
<div class="container-fluid home-index p-5">
    <div class="container text-center">         
        <div class="container" id='wrap'>
            <div class="container d-flex justify-self-center mt-5 pb-3">
                <div class="table-responsive col mt-5">
                    <h1 class="text-center">Cadastro do Professor</h1>
                    <form action="" method="post">
                        {% csrf_token %}
                        <table class="table">
                            <tbody>
                                <tr>
                                    {{ form.as_table }}
                                </tr> 
                            </tbody>
                        </table>
                        <div class="container d-flex justify-content-center">
                            <input type="submit" class="btn btn-primary btn-lg" value="Salvar">
                            <input type="submit" class="btn btn-danger btn-lg" onclick="window.location='{% url 'teacher_all' %}'; return false;" value="Cancelar">
                        </div>    
                    </form> 

                </div>
            </div>
        </div>
    </div>
</div>
<<<<<<< HEAD
<!-- END BOOTSTRAP FORM -->

>>>>>>> ee2e9db (add, configurate and edit app teacher)
=======
>>>>>>> 646d419 (delete files)
{% endblock %}

teacher/templates/teacher/teacher_group.html
{% extends "base.html" %}
{% load static %}


{% block content %}
    <div class="container p-2 bg-white mostly-customized-scrollbar"id="body-grid">
            <h1 class="text-center p-5">{{ object }}</h1>
        <div class="schedule">
            <!-- days -->
            <span class="day" aria-hidden="true" style="grid-column: sunday; grid-row: days;">Domingo</span>
            <span class="day" aria-hidden="true" style="grid-column: monday; grid-row: days;">Segunda-Feira </span>
            <span class="day" aria-hidden="true" style="grid-column: tuesday; grid-row: days;">Terça-Feira</span>
            <span class="day" aria-hidden="true" style="grid-column: wednesday; grid-row: days;">Quarta-Feira</span>
            <span class="day" aria-hidden="true" style="grid-column: thursday; grid-row: days;">Quinta-Feira</span>
            <span class="day" aria-hidden="true" style="grid-column: friday; grid-row: days;">Sexta-Feira</span>
            <span class="day" aria-hidden="true" style="grid-column: saturday; grid-row: days;">Sábado</span>

            {% if group.turn.id == 1 %}
                <!-- time slots -->
                <h2 class="time" style="grid-column: times; grid-row: time-0700;">07:00</h2>
                <h2 class="time" style="grid-column: times; grid-row: time-0730;">07:30</h2>
                <h2 class="time" style="grid-column: times; grid-row: time-0800;">08:00</h2>    
                <h2 class="time" style="grid-column: times; grid-row: time-0830;">08:30</h2>   
                <h2 class="time" style="grid-column: times; grid-row: time-0900;">09:00</h2>
                <h2 class="time" style="grid-column: times; grid-row: time-0915;">09:15</h2>
                <h2 class="time" style="grid-column: times; grid-row: time-0930;">09:30</h2>
                <h2 class="time" style="grid-column: times; grid-row: time-1000;">10:00</h2>
                <h2 class="time" style="grid-column: times; grid-row: time-1030;">10:30</h2>
                <h2 class="time" style="grid-column: times; grid-row: time-1100;">11:00</h2>
                <h2 class="time" style="grid-column: times; grid-row: time-1130;">11:30</h2>
                <h2 class="time" style="grid-column: times; grid-row: time-1200;">12:00</h2>       
                <h2 class="time" style="grid-column: times; grid-row: time-1230;">12:30</h2>    
            {% endif %}
            
                
            {% for grid in grid_group %}
                
                    {% if grid.teacher == teacher %}
                        <div class="session subject-0 {{ grid.dicipline }}" style="grid-column: {{ grid.day_week }}; grid-row: time-{{ grid.get_start }} / time-{{ grid.get_end_lesson }};">
                            <h3 class="time"></h3>
                            <h3 class="subject">{{ grid.get_dicipline_display }}</h3>
                            <span class="time">Início: {{ grid.time_start }}</span>
                            <span class="time"><p class="small">Duração: {{grid.get_duration_time}}</p></span>
                            <span class="description">{{grid.description}}</span>
                            <span class="teacher"><p class="small">{{grid.group}}</p></span>
                        </div>
                    {% endif %}                    
            {% endfor %}
            
            {% if group.interval_start %}
            
                <!-- breaks -->
                <div class="session breaks" style="grid-column: monday-start / friday-end; grid-row: time-{{ group.get_start }} / time-{{ group.get_interval_end }};">
                    <h3 class="subject">Intervalo</h3>
                </div>
            
            {% endif %}
        </div>
    </div>
{% endblock content %}

teacher/templates/teacher/teacher_list.html
{% extends 'base.html' %}

{% load static humanize %}

{% block content %}

<<<<<<< HEAD
    <div class="container-fluid home-index p-5">
        <div class="container text-center"> 
            <div class="container" id='wrap'>
                <div class="table-responsive col">
                    <h1 class="text-center pt-4">Professores</h1>
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th class="text-center" scope="col">Nome</th>
                                <th class="text-center" scope="col">Sobrenome</th>
                                <th class="text-center" scope="col">Telefone</th>
                                <th class="text-center" scope="col">E-mail</th>
                                {% if perms.teacher.delete_teacher %}
                                    <th class="text-center" scope="col">Alterar</th>
                                {% endif %}
                                {% if perms.teacher.delete_teacher %}
                                    <th class="text-center" scope="col">Excluir</th>
                                {% endif %}
                            </tr>
                        </thead>
                        <tbody>
                        
                            {% for teacher in teacher_list %}
                            <tr>
                                <th scope="row">{{ forloop.counter }}</th>
                                {% if perms.teacher.view_teatcher %}
                                    <td class="ml-5"><a href="{% url 'teacher_detail' teacher.id %}">Prof. {{ teacher.first_name|title }}</a></td>
                                {% else %}
                                    <td clSass="ml-5">Prof. {{ teacher.first_name|title }}</td>
                                {% endif %}
                                <td class="text-center">{{ teacher.last_name|title }}</td>
                                <td class="text-center">({{ teacher.phone_ddd }}) {{ teacher.phone_number }}</td>
                                <td class="text-center">{{ teacher.email }}</td>
                                
                                {% if perms.teacher.add_teacher %}
                                    <td class="text-center"><a href="#">
                                        <i class="bi bi-pencil-square text-success"></i>
                                    </a></td>
                                {% endif %}

                                {% if perms.teacher.delete_teacher %}
                                    <td class="text-center"><a href="#">
                                        <i class="bi bi-trash3 text-danger"></i>
                                    </a></td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    
                        </tbody>
                    </table>    
                </div>
                {% if perms.teacher.add_teacher %}
                    <div class="d-flex justify-content-center">
                        <a href="{% url 'teacher_new' %}" class="d-block btn btn-success btn-lg my-5 mx-2 my-2">Novo Cadastro</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
=======
    {% include 'parciais/_navbar.html' %}

<div class="container-fluid home-index p-5">
    <div class="container text-center"> 
        <div class="container" id='wrap'>
            <div class="table-responsive col">
                <h1 class="text-center pt-4">Professores</h1>
                <div class="col mt-5 image_school_2"></div>  
                <table class="table table-striped">
                    {% include 'parciais/_pagination.html' %}
                    <thead>
                        <tr>
                            <th>#</th>
                            <th class="text-center" scope="col">Nome</th>
                            <th class="text-center" scope="col">Sobrenome</th>
                            <th class="text-center" scope="col">Telefone</th>
                            <th class="text-center" scope="col">E-mail</th>
                            <th class="text-center" scope="col">Alterar</th>
                            <th class="text-center" scope="col">Excluir</th>
                        </tr>
                    </thead>
                    <tbody>
                    
                        {% for teacher in teacher_list %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            {% if perms.teacher.view_teatcher %}
                                <td class="ml-5"><a href="{% url 'teacher_detail' teacher.id %}">Prof. {{ teacher.first_name|title }}</a></td>
                            {% else %}
                                <td clSass="ml-5">Prof. {{ teacher.first_name|title }}</td>
                            {% endif %}
                            <td class="text-center">{{ teacher.last_name|title }}</td>
                            <td class="text-center">({{ teacher.phone_ddd }}) {{ teacher.phone_number }}</td>
                            <td class="text-center">{{ teacher.email }}</td>
                            
                            {% if perms.teacher.change_teacher %}
                                <td class="text-center"><a href="{% url 'teacher_update' teacher.id %}">
                                    <i class="bi bi-pencil-square text-success"></i>
                                </a></td>
                            {% endif %}

                            {% if perms.teacher.delete_teacher %}
                                <td class="text-center"><a href="{% url 'teacher_delete' teacher.id %}">
                                    <i class="bi bi-trash3 text-danger"></i>
                                </a></td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                
                    </tbody>
                </table>    
            </div>
            {% if perms.teacher.add_teacher %}
                <div class="d-flex justify-content-center">
                    <a href="{% url 'teacher_create' %}" class="d-block btn btn-primary btn-lg my-5 mx-2 my-2">Novo Cadastro</a>
                </div>
            {% else %}
                não tem permissões
            {% endif %}
        </div>
    </div>
<<<<<<< HEAD

>>>>>>> ee2e9db (add, configurate and edit app teacher)
=======
</div>
>>>>>>> 646d419 (delete files)
{% endblock content %}