core/urls.py
from django.urls import path, include
<<<<<<< HEAD
from .views import IndexView, page_not_found, server_error
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("500/", server_error, name="server_error"),
    path("404/", page_not_found, name="page_not_found"),
=======

from .views import IndexView
from core.views import pagina_nao_encontrada, erro_servidor

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
<<<<<<< HEAD
>>>>>>> a8c0174 (include core app and configs)
=======
    path("404/", pagina_nao_encontrada, name="pagina_nao_encontrada"),
    path("500/", erro_servidor, name="erro_servidor")
>>>>>>> d3380e7 (add corrections)
]

# paginas e Erro
handler404 = 'core.views.pagina_nao_encontrada'
handler500 = 'core.views.erro_servidor'

pi1tg18/urls.py
from django.contrib import admin
<<<<<<< HEAD
from django.urls import path
=======
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
<<<<<<< HEAD
<<<<<<< HEAD
from django.views.generic import TemplateView

>>>>>>> 86a1e24 (preparing static file folder and template with html test)
=======
from schedule.views import all_events
>>>>>>> a8c0174 (include core app and configs)
=======
from schedule.views import all_events
>>>>>>> 16093fb (created app schedule, config and tests)

urlpatterns = [
    path("", include('core.urls')),
    path('accounts/', include('allauth.urls')),
    path("schedule/", include('schedule.urls')),
    path("school/", include('school.urls')),
    path("teacher/", include('teacher.urls')),
    path("student/", include('student.urls')),
    path("discipline/", include('discipline.urls')),
    path("group/", include('group.urls')),
    path('admin/', admin.site.urls),
    path("all_events/", all_events, name="all_events"),

]
<<<<<<< HEAD
=======

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns


# paginas e Erro
handler404 = 'core.views.pagina_nao_encontrada'
handler500 = 'core.views.erro_servidor'
>>>>>>> d3380e7 (add corrections)

school/urls.py
<<<<<<< HEAD
<<<<<<< HEAD
from django.urls import path, include

from .views import *


urlpatterns = [
    path("group/", IndexView.as_view(), name="school_index"),
    path("", SchoolListView.as_view(), name="school_all"),
    path('<int:pk>/update/', SchoolUpdateView.as_view(), name='school_update'),
    path("<int:pk>/detail/", SchoolDetailView.as_view(), name="school_detail"),
    path("<int:pk>/phones/", PhoneSchoolListView.as_view(), name="phones_school_all"),
    path("<int:pk>/address/", AddressSchoolListView.as_view(), name="address_school_all"),
=======
from .views import SchoolCreateView, SchoolDeleteView, SchoolDetailView, SchoolUpdateView, SchoolListView
=======
from .views import SchoolCreateView, SchoolDeleteView, SchoolDetailView, SchoolUpdateView, SchoolListView, StructListView, StructCreateView, StructDeleteView, StructDetailView, StructUpdateView
>>>>>>> 98c1c6d (corrects on apps)
from django.urls import path


urlpatterns = [
    path("", SchoolListView.as_view(), name="school_all"),
    path('<int:pk>/detail/', SchoolDetailView.as_view(), name='school_detail'),
    path('new/', SchoolCreateView.as_view(), name='school_create'),
    path('<int:pk>/update/', SchoolUpdateView.as_view(), name='school_update'),
    path('<int:pk>/delete/', SchoolDeleteView.as_view(), name='school_delete'),
<<<<<<< HEAD
>>>>>>> 70b58ba (add app school and config pages)
=======
    path("struct/", StructListView.as_view(), name="struct_all"),
    path('struct/new/', StructCreateView.as_view(), name='struct_create'),
    path('struct/<int:pk>/update/',
         StructUpdateView.as_view(), name='struct_update'),
    path('struct/<int:pk>/delete/',
         StructDeleteView.as_view(), name='struct_delete'),
>>>>>>> 98c1c6d (corrects on apps)
]

school/models.py
<<<<<<< HEAD
from datetime import datetime
from django.db import models
from django.utils.translation import gettext_lazy as _

from core.models import Address, PhoneBase

from .utils import weeks, number_week, days_week

class School(models.Model):

    name = models.CharField(_("Nome da Escola"), max_length=100)
    fantasy_name = models.CharField(_("Apelido"), max_length=30)
    email = models.EmailField(_("E-mail"), max_length=254)

    class Meta:
        verbose_name = _("Escola")
        verbose_name_plural = _("Escolas")

    def __str__(self):
        return self.name.title()

    def get_fantasy(self):
        return self.fantasy_name.title()


class AddressSchool(models.Model):

    school = models.OneToOneField(
        School,
        verbose_name=_("Escola"),
        on_delete=models.CASCADE,
    )
    address = models.ForeignKey(
        Address,
        verbose_name=_("Endereço"),
        on_delete=models.PROTECT,
    )
    number = models.IntegerField(_("Número"))
    complement = models.CharField(_("Complemento"), max_length=20, blank=True, null=True)


    class Meta:
        verbose_name = _("Endereço da Escola")
        verbose_name_plural = _("Endereços da Escola")

    @property
    def get_zip_code(self):
        return self.address.zip_code
    
    @property
    def get_address(self):
        return self.address.get_type_address
    
    @property
    def get_city_state(self):
        return self.address.city.get_cityuf
    
    def __str__(self):
        return f'CEP: {self.get_zip_code} - Endereço: {self.get_address()}, {self.number}, {self.complement} - {self.get_city_state()}'


class PhoneSchool(PhoneBase):

    CELULAR = 'C'
    PRINCIPAL = 'P'
    WHATSAPP = 'W'
    TELEGRAN = 'T'
    OUTRO = 'O'
    PHONE_TYPE_CHOICES = {
        CELULAR: 'Celular',
        PRINCIPAL: 'Principal',
        WHATSAPP: 'Whatsapp',
        TELEGRAN: 'Telegran',
        OUTRO: 'Outro',
    }
    school = models.ForeignKey(
        School, 
        verbose_name=_("escola"),
        on_delete=models.CASCADE)
    phone_type = models.CharField(
        max_length=1,
        choices=PHONE_TYPE_CHOICES,
        default=PRINCIPAL,
    )

    @property
    def get_phone(self):
        prefix = ''
        if self.country_code:
            prefix = f'+{self.country_code}'
        if self.locale_code:
            prefix += f'({self.locale_code})'
        
        return f'{prefix} {self.number}'
    
    def is_upperclass(self):
        return self.phone_type in {self.CELULAR, self.PRINCIPAL}

    class Meta:
        verbose_name = _("Telefone da Escola")
        verbose_name_plural = _("Telefones da Escola")

    def __str__(self):
        return f'+{self.country_code}({self.locale_code}) {self.number}'


class TurnSchool(models.Model):

    name = models.CharField(_("Nome do Turno"), max_length=10)
    school = models.ForeignKey(
        School, 
        verbose_name=_("Escola"), 
        on_delete=models.PROTECT,
    )
    start_time = models.TimeField(_("Hora de Início"))
    duration = models.DurationField(_("Duração"))

    class Meta:
        verbose_name = _("Turno Escolar")
        verbose_name_plural = _("Turnos da Escola")

    def __str__(self):
        return self.name.title()

class ClassRoom(models.Model):
    PADRAO = 'P'
    ESPECIAL = 'E'
    INFORMATICA = 'N'
    LABORATORIO = 'L'
    INCLUSIVA = 'I'
    OUTRA = 'O'
    CLASSROOM_TYPE_CHOICES = {
        PADRAO: _('Padrão'),
        ESPECIAL: _('Especial'),
        INFORMATICA: _('Informática'),
        LABORATORIO: _('Laboratório'),
        INCLUSIVA: _('Inclusiva'),
        OUTRA: _('Outra')
    }
        
    identification = models.CharField(_("Identificação"), max_length=5)
    vacation = models.PositiveIntegerField(_("Vagas"))
    classroom_tyoe = models.CharField(
        _("Tipo de Classe de Aula"),
        max_length=1,
        choices=CLASSROOM_TYPE_CHOICES
    )
    school = models.ForeignKey(
        School,
        verbose_name=_("Escola"),
        on_delete=models.PROTECT,
    )
    class Meta:
        verbose_name = _("Sala de Aula")
        verbose_name_plural = _("Salas de Aula")

    def __str__(self):
        return f'Sala {self.identification}'


class SchoolYear(models.Model):
    school = models.ForeignKey(
        School, 
        verbose_name=_("Escola"), 
        on_delete=models.CASCADE
    )
    first_start = models.DateField(_("Inicio ano letivo"))
    halfyear_start = models.DateField(_("Inicio Ferias"))
    second_start = models.DateField(_("Inicio 2º Semestre"))
    end = models.DateField(_("Termino ano letivo"), auto_now=False, auto_now_add=False)

    @property
    def first_semester(self) -> dict:
        start = datetime(year=self.first_start.year, month=self.first_start.month, day=self.first_start.day)
        end = datetime(year=self.halfyear_start.year,month=self.halfyear_start.month,day=self.halfyear_start.day)
        
        n_week = sorted(number_week(weeks(start, end)))
        dict = {
            'start': start,
            'end': end,
            'weeks': list(n_week),
        }
        return dict
    
    
    @property
    def second_semester(self) -> dict:
        start = datetime(year=self.second_start.year, month=self.second_start.month, day=self.second_start.day)
        end = datetime(year=self.end.year,month=self.end.month,day=self.end.day)
        
        n_week = sorted(number_week(weeks(start, end)))
        dict = {
            'start': start,
            'end': end,
            'weeks': list(n_week),
        }
        return dict
    
    
        
    class Meta:
        verbose_name = _("Ano Letivo")
        verbose_name_plural = _("Anos Letivos")

    def __str__(self):
        return f'Ano: {self.first_start.year}'
    
    
=======
from django.db import models
from django.utils.translation import gettext_lazy as _
from core.models import TimeStamp


class StructTypeChoice(models.TextChoices):
    SALADEAULA = 'SLAU', _('Sala de Aula')
    QUADRAPOLIESPORTIVA = 'QPE', _('Quadra Poliesportiva')
    ESPACORECREACAO = 'ESPR', _('Espaço de Recreação')
    SALAINFORMATIVA = 'SLIN', _('Sala de Informatica/Computação')
    LABORATORIO = 'LAB', _('Laboratório')
    PROFESSORES = 'PROF', _('Sala dos Professores')


class School(TimeStamp):

    name = models.CharField(_("Nome da Escola"), max_length=150)
    fantasy = models.CharField(_("Nome Fantasia"), max_length=25, null=True, blank=True)
    cnpj_number = models.CharField(_("CNPJ da Escola"), max_length=18)
    school_number = models.CharField(
        _("Numero Cadastro Secretaria"), max_length=20)

    address_zipcode = models.CharField(_("CEP"), max_length=9)
    address = models.CharField(_("Endereço"), max_length=150)
    address_number = models.CharField(_("Número"), max_length=5)
    address_complement = models.CharField(_("Complemento"), max_length=20)
    address_district = models.CharField(_("Bairro"), max_length=50)
    address_city = models.CharField(_("Cidade"), max_length=70)
    address_state = models.CharField(_("UF"), max_length=2)

    email = models.EmailField(_("E-mail"), max_length=254)
    phone_ddd = models.CharField(_("DDD"), max_length=4)
    phone_number = models.CharField(_("Phone"), max_length=9)

    class Meta:
        """Meta definition for School."""

        verbose_name = 'Escola'
        verbose_name_plural = 'Escola'

    def get_fields(self):
        return [(field.verbose_name, field.value_from_object(self))
                for field in self.__class__._meta.fields[1:]
                ]

    def __str__(self):
        """Unicode representation of School."""
        return self.name.upper()

    def save_model(self, request, obj, form, change):
        if not change:
            obj.user = request.user
            obj.save()
        super(School, self).save_model(request, obj, form, change)


class StructSchool(models.Model):

    school = models.ForeignKey(
        School, verbose_name=_("Escola"), on_delete=models.CASCADE)
    
    struct_type = models.CharField(
        _("Estrutura"), max_length=4, choices=StructTypeChoice.choices)
    
    name = models.CharField(_("Identificação"), max_length=50)
    
    vagas = models.IntegerField(_("Quantidade de vagas"))
    height = models.IntegerField(_("Altura (m)"), blank=True, null=True)
    width = models.IntegerField(_("Largura (m)"), blank=True, null=True)
    length = models.IntegerField(_("Comprimento (m)"), blank=True, null=True)
    area = models.IntegerField(_("Area (m²)"))
    perimeter = models.IntegerField(_("Perímetro (m)"))
    

    class Meta:
        """Meta definition for StructSchool."""

        verbose_name = 'StructSchool'
        verbose_name_plural = 'StructSchools'

    def __str__(self):
        """Unicode representation of StructSchool."""
        return f'{self.struct_type} {self.name}'
<<<<<<< HEAD
>>>>>>> 70b58ba (add app school and config pages)
=======

    def full_name_struct(self):
        return f'{self.struct_type.get.display}'
<<<<<<< HEAD
>>>>>>> 93b9589 (add and config new app group)
=======
    
    def get_fields(self):
        return [(field.verbose_name, field.value_from_object(self))
                for field in self.__class__._meta.fields[1:]
                ]
>>>>>>> d22ecf1 (correctons apps school. schedule, core)

school/forms.py
from django import forms
<<<<<<< HEAD

from .models import School


class SchoolForm(forms.ModelForm):
    
    class Meta:
        model = School
        fields = '__all__'
=======
from django.utils.translation import gettext_lazy as _
from .models import School, StructSchool


class SchoolForm(forms.ModelForm):

    class Meta:
        model = School
        fields = '__all__'


class StructSchoolForm(forms.ModelForm):

    class Meta:
        model = StructSchool
        fields = '__all__'
>>>>>>> 70b58ba (add app school and config pages)

school/templates/school/crud/address/list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="container-fluid home-index p-5">
        <div class="container text-center"> 
            <div class="container" id='wrap'>
                <div class="table-responsive col">
                    <h1 class="text-center p-4">Endereço da Escola</h1>        
                    <table class="table">
                        {% comment %} {% include 'parciais/_pagination.html' %} {% endcomment %}
                        <thead>
                            <tr>
                                <th class="text-center" scope="col">CEP</th>
                                <th class="text-center" scope="col">Tipo</th>
                                <th class="text-center" scope="col">Endereço</th>
                                <th class="text-center" scope="col">Número</th>
                                <th class="text-center" scope="col">Complemento</th>
                                <th class="text-center" scope="col">Bairro</th>
                                <th class="text-center" scope="col">Cidade</th>
                                <th class="text-center" scope="col">UF</th>
                                {% if perms.school.delete_school %}
                                    <th class="text-center" scope="col">Alterar</th>
                                {% endif %}
                                {% if perms.school.delete_school %}
                                    <th class="text-center" scope="col">Excluir</th>
                                {% endif %}
                            </tr>
                        </thead>
                        <tbody>
                        
                            {% for address in addressschool_list %}
                            <tr>
                                <td class="text-center">{{ address.zip_code }}</td>
                                <td class="text-center">{{ address.get_type_display }}</td>
                                <td class="text-center"> {{ address.address }}</td>
                                <td class="text-center">{{ address.number }}</td>
                                <td class="text-center">{{ address.complement }}</td>
                                <td class="text-center"> {{ address.district }}</td>
                                <td class="text-center">{{ address.city }}</td>
                                <td class="text-center">{{ address.city.state }}</td>
                                {% if perms.school.add_school %}
                                <td class="text-center"><a href="#">
                                    <i class="bi bi-pencil-square text-success"></i>
                                </a></td>
                                {% endif %}
                                {% if perms.school.delete_school %}
                                <td class="text-center"><a href="#">
                                    <i class="bi bi-trash3 text-danger"></i>
                                </a></td>
                                {% endif %}
                            </tr>
                        {% endfor %}                    
                        </tbody>
                    </table>
                    <div class="btn-group pb-2">                        
                        {% comment %} {% if perms.group.change_group %} {% endcomment %}
                        <a href="#">
                            <button type="button" class="btn btn-sm btn-outline-success">Novo</button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}