core/urls.py
from django.urls import path, include
<<<<<<< HEAD
from .views import IndexView, page_not_found, server_error
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("500/", server_error, name="server_error"),
    path("404/", page_not_found, name="page_not_found"),
=======

from .views import IndexView
from core.views import pagina_nao_encontrada, erro_servidor

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
<<<<<<< HEAD
>>>>>>> a8c0174 (include core app and configs)
=======
    path("404/", pagina_nao_encontrada, name="pagina_nao_encontrada"),
    path("500/", erro_servidor, name="erro_servidor")
>>>>>>> d3380e7 (add corrections)
]

# paginas e Erro
handler404 = 'core.views.pagina_nao_encontrada'
handler500 = 'core.views.erro_servidor'

pi1tg18/urls.py
from django.contrib import admin
<<<<<<< HEAD
from django.urls import path
=======
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
<<<<<<< HEAD
<<<<<<< HEAD
from django.views.generic import TemplateView

>>>>>>> 86a1e24 (preparing static file folder and template with html test)
=======
from schedule.views import all_events
>>>>>>> a8c0174 (include core app and configs)
=======
from schedule.views import all_events
>>>>>>> 16093fb (created app schedule, config and tests)

urlpatterns = [
    path("", include('core.urls')),
    path('accounts/', include('allauth.urls')),
    path("schedule/", include('schedule.urls')),
    path("school/", include('school.urls')),
    path("teacher/", include('teacher.urls')),
    path("student/", include('student.urls')),
    path("discipline/", include('discipline.urls')),
    path("group/", include('group.urls')),
    path('admin/', admin.site.urls),
    path("all_events/", all_events, name="all_events"),

]
<<<<<<< HEAD
=======

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns


# paginas e Erro
handler404 = 'core.views.pagina_nao_encontrada'
handler500 = 'core.views.erro_servidor'
>>>>>>> d3380e7 (add corrections)

school/models.py
<<<<<<< HEAD
from datetime import datetime
from django.db import models
from django.utils.translation import gettext_lazy as _

from core.models import Address, PhoneBase

from .utils import weeks, number_week, days_week

class School(models.Model):

    name = models.CharField(_("Nome da Escola"), max_length=100)
    fantasy_name = models.CharField(_("Apelido"), max_length=30)
    email = models.EmailField(_("E-mail"), max_length=254)

    class Meta:
        verbose_name = _("Escola")
        verbose_name_plural = _("Escolas")

    def __str__(self):
        return self.name.title()

    def get_fantasy(self):
        return self.fantasy_name.title()


class AddressSchool(models.Model):

    school = models.OneToOneField(
        School,
        verbose_name=_("Escola"),
        on_delete=models.CASCADE,
    )
    address = models.ForeignKey(
        Address,
        verbose_name=_("Endereço"),
        on_delete=models.PROTECT,
    )
    number = models.IntegerField(_("Número"))
    complement = models.CharField(_("Complemento"), max_length=20, blank=True, null=True)


    class Meta:
        verbose_name = _("Endereço da Escola")
        verbose_name_plural = _("Endereços da Escola")

    @property
    def get_zip_code(self):
        return self.address.zip_code
    
    @property
    def get_address(self):
        return self.address.get_type_address
    
    @property
    def get_city_state(self):
        return self.address.city.get_cityuf
    
    def __str__(self):
        return f'CEP: {self.get_zip_code} - Endereço: {self.get_address()}, {self.number}, {self.complement} - {self.get_city_state()}'


class PhoneSchool(PhoneBase):

    CELULAR = 'C'
    PRINCIPAL = 'P'
    WHATSAPP = 'W'
    TELEGRAN = 'T'
    OUTRO = 'O'
    PHONE_TYPE_CHOICES = {
        CELULAR: 'Celular',
        PRINCIPAL: 'Principal',
        WHATSAPP: 'Whatsapp',
        TELEGRAN: 'Telegran',
        OUTRO: 'Outro',
    }
    school = models.ForeignKey(
        School, 
        verbose_name=_("escola"),
        on_delete=models.CASCADE)
    phone_type = models.CharField(
        max_length=1,
        choices=PHONE_TYPE_CHOICES,
        default=PRINCIPAL,
    )

    @property
    def get_phone(self):
        prefix = ''
        if self.country_code:
            prefix = f'+{self.country_code}'
        if self.locale_code:
            prefix += f'({self.locale_code})'
        
        return f'{prefix} {self.number}'
    
    def is_upperclass(self):
        return self.phone_type in {self.CELULAR, self.PRINCIPAL}

    class Meta:
        verbose_name = _("Telefone da Escola")
        verbose_name_plural = _("Telefones da Escola")

    def __str__(self):
        return f'+{self.country_code}({self.locale_code}) {self.number}'


class TurnSchool(models.Model):

    name = models.CharField(_("Nome do Turno"), max_length=10)
    school = models.ForeignKey(
        School, 
        verbose_name=_("Escola"), 
        on_delete=models.PROTECT,
    )
    start_time = models.TimeField(_("Hora de Início"))
    duration = models.DurationField(_("Duração"))

    class Meta:
        verbose_name = _("Turno Escolar")
        verbose_name_plural = _("Turnos da Escola")

    def __str__(self):
        return self.name.title()

class ClassRoom(models.Model):
    PADRAO = 'P'
    ESPECIAL = 'E'
    INFORMATICA = 'N'
    LABORATORIO = 'L'
    INCLUSIVA = 'I'
    OUTRA = 'O'
    CLASSROOM_TYPE_CHOICES = {
        PADRAO: _('Padrão'),
        ESPECIAL: _('Especial'),
        INFORMATICA: _('Informática'),
        LABORATORIO: _('Laboratório'),
        INCLUSIVA: _('Inclusiva'),
        OUTRA: _('Outra')
    }
        
    identification = models.CharField(_("Identificação"), max_length=5)
    vacation = models.PositiveIntegerField(_("Vagas"))
    classroom_tyoe = models.CharField(
        _("Tipo de Classe de Aula"),
        max_length=1,
        choices=CLASSROOM_TYPE_CHOICES
    )
    school = models.ForeignKey(
        School,
        verbose_name=_("Escola"),
        on_delete=models.PROTECT,
    )
    class Meta:
        verbose_name = _("Sala de Aula")
        verbose_name_plural = _("Salas de Aula")

    def __str__(self):
        return f'Sala {self.identification}'


class SchoolYear(models.Model):
    school = models.ForeignKey(
        School, 
        verbose_name=_("Escola"), 
        on_delete=models.CASCADE
    )
    first_start = models.DateField(_("Inicio ano letivo"))
    halfyear_start = models.DateField(_("Inicio Ferias"))
    second_start = models.DateField(_("Inicio 2º Semestre"))
    end = models.DateField(_("Termino ano letivo"), auto_now=False, auto_now_add=False)

    @property
    def first_semester(self) -> dict:
        start = datetime(year=self.first_start.year, month=self.first_start.month, day=self.first_start.day)
        end = datetime(year=self.halfyear_start.year,month=self.halfyear_start.month,day=self.halfyear_start.day)
        
        n_week = sorted(number_week(weeks(start, end)))
        dict = {
            'start': start,
            'end': end,
            'weeks': list(n_week),
        }
        return dict
    
    
    @property
    def second_semester(self) -> dict:
        start = datetime(year=self.second_start.year, month=self.second_start.month, day=self.second_start.day)
        end = datetime(year=self.end.year,month=self.end.month,day=self.end.day)
        
        n_week = sorted(number_week(weeks(start, end)))
        dict = {
            'start': start,
            'end': end,
            'weeks': list(n_week),
        }
        return dict
    
    
        
    class Meta:
        verbose_name = _("Ano Letivo")
        verbose_name_plural = _("Anos Letivos")

    def __str__(self):
        return f'Ano: {self.first_start.year}'
    
    
=======
from django.db import models
from django.utils.translation import gettext_lazy as _
from core.models import TimeStamp


class StructTypeChoice(models.TextChoices):
    SALADEAULA = 'SLAU', _('Sala de Aula')
    QUADRAPOLIESPORTIVA = 'QPE', _('Quadra Poliesportiva')
    ESPACORECREACAO = 'ESPR', _('Espaço de Recreação')
    SALAINFORMATIVA = 'SLIN', _('Sala de Informatica/Computação')
    LABORATORIO = 'LAB', _('Laboratório')
    PROFESSORES = 'PROF', _('Sala dos Professores')


class School(TimeStamp):

    name = models.CharField(_("Nome da Escola"), max_length=150)
    fantasy = models.CharField(_("Nome Fantasia"), max_length=25, null=True, blank=True)
    cnpj_number = models.CharField(_("CNPJ da Escola"), max_length=18)
    school_number = models.CharField(
        _("Numero Cadastro Secretaria"), max_length=20)

    address_zipcode = models.CharField(_("CEP"), max_length=9)
    address = models.CharField(_("Endereço"), max_length=150)
    address_number = models.CharField(_("Número"), max_length=5)
    address_complement = models.CharField(_("Complemento"), max_length=20)
    address_district = models.CharField(_("Bairro"), max_length=50)
    address_city = models.CharField(_("Cidade"), max_length=70)
    address_state = models.CharField(_("UF"), max_length=2)

    email = models.EmailField(_("E-mail"), max_length=254)
    phone_ddd = models.CharField(_("DDD"), max_length=4)
    phone_number = models.CharField(_("Phone"), max_length=9)

    class Meta:
        """Meta definition for School."""

        verbose_name = 'Escola'
        verbose_name_plural = 'Escola'

    def get_fields(self):
        return [(field.verbose_name, field.value_from_object(self))
                for field in self.__class__._meta.fields[1:]
                ]

    def __str__(self):
        """Unicode representation of School."""
        return self.name.upper()

    def save_model(self, request, obj, form, change):
        if not change:
            obj.user = request.user
            obj.save()
        super(School, self).save_model(request, obj, form, change)


class StructSchool(models.Model):

    school = models.ForeignKey(
        School, verbose_name=_("Escola"), on_delete=models.CASCADE)
    
    struct_type = models.CharField(
        _("Estrutura"), max_length=4, choices=StructTypeChoice.choices)
    
    name = models.CharField(_("Identificação"), max_length=50)
    
    vagas = models.IntegerField(_("Quantidade de vagas"))
    height = models.IntegerField(_("Altura (m)"), blank=True, null=True)
    width = models.IntegerField(_("Largura (m)"), blank=True, null=True)
    length = models.IntegerField(_("Comprimento (m)"), blank=True, null=True)
    area = models.IntegerField(_("Area (m²)"))
    perimeter = models.IntegerField(_("Perímetro (m)"))
    

    class Meta:
        """Meta definition for StructSchool."""

        verbose_name = 'StructSchool'
        verbose_name_plural = 'StructSchools'

    def __str__(self):
        """Unicode representation of StructSchool."""
        return f'{self.struct_type} {self.name}'
<<<<<<< HEAD
>>>>>>> 70b58ba (add app school and config pages)
=======

    def full_name_struct(self):
        return f'{self.struct_type.get.display}'
<<<<<<< HEAD
>>>>>>> 93b9589 (add and config new app group)
=======
    
    def get_fields(self):
        return [(field.verbose_name, field.value_from_object(self))
                for field in self.__class__._meta.fields[1:]
                ]
>>>>>>> d22ecf1 (correctons apps school. schedule, core)

teacher/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
<<<<<<< HEAD
from django.urls import reverse

from core.models import City, Address, PhoneBase
from school.models import School

class Teacher(models.Model):

    first_name = models.CharField(_("Nome"), max_length=20)
    last_name = models.CharField(_("Sobrenome"), max_length=70)
    email = models.EmailField(_("E-mail"), max_length=254)
    school = models.ForeignKey(
        School, 
        verbose_name=_("Escola"), 
        on_delete=models.PROTECT,
    )

    @property
    def full_name(self):
        return f'{self.first_name.title()} {self.last_name.title()}'
    
    class Meta:
        verbose_name = _("Professor(a)")
        verbose_name_plural = _("Professores")

    def __str__(self):
        return self.full_name
    
    def get_absolute_url(self):
        
        return reverse('teacher_detail', kwargs={'pk': self.pk})

class AddressTeacher(models.Model):

    zipcode = models.OneToOneField(
        Address, 
        verbose_name=_("CEP"),
        on_delete=models.PROTECT
    )
    number = models.PositiveIntegerField(_("Número"))
    complement = models.CharField(_("Complemento"), max_length=20, null=True, blank=True)
    teacher = models.ForeignKey(
        Teacher, 
        verbose_name=_("Professor"),
        on_delete=models.CASCADE,
    )
    
    class Meta:
        verbose_name = _("Endereço do Professor(a)")
        verbose_name_plural = _("Endereços do Professor(a)")

    def __str__(self):
        return self.zipcode.get_address()

class PhoneTeacher(PhoneBase):

    CELULAR = 'C'
    PRINCIPAL = 'P'
    WHATSAPP = 'W'
    TELEGRAN = 'T'
    OUTRO = 'O'
    PHONE_TYPE_CHOICES = {
        CELULAR: 'Celular',
        PRINCIPAL: 'Principal',
        WHATSAPP: 'Whatsapp',
        TELEGRAN: 'Telegran',
        OUTRO: 'Outro',
    }
    teacher = models.ForeignKey(
        Teacher, 
        verbose_name=_("Professor"),
        on_delete=models.CASCADE)
    phone_type = models.CharField(
        max_length=1,
        choices=PHONE_TYPE_CHOICES,
        default=PRINCIPAL,
    )

    @property
    def get_phone(self):
        prefix = ''
        if self.country_code:
            prefix = f'+{self.country_code}'
        if self.locale_code:
            prefix += f'({self.locale_code})'
        
        return f'{prefix} {self.number}'
    
    def is_upperclass(self):
        return self.phone_type in {self.CELULAR, self.PRINCIPAL}

    class Meta:
        verbose_name = _("Telefone do Professor(a)")
        verbose_name_plural = _("Telefones do Professor(a)")

    def __str__(self):
        return f'+{self.country_code}({self.locale_code}) {self.number}'
=======

from core.models import TimeStamp
from school.models import School


class Teacher(TimeStamp):

    school = models.ForeignKey(
        School,
        verbose_name=_("Escola"),
        on_delete=models.DO_NOTHING)

    first_name = models.CharField(_("Primeiro Nome"), max_length=50)
    last_name = models.CharField(_("Sobrenome"), max_length=70)

    email = models.EmailField(_("E-mail"), max_length=254)

    phone_ddd = models.CharField(_("DDD"), max_length=4)
    phone_number = models.CharField(_("Telefone"), max_length=9)

    address_zipcode = models.CharField(_("CEP"), max_length=9)
    address = models.CharField(_("Endereço"), max_length=150)
    address_number = models.CharField(_("Número"), max_length=5)
    address_complement = models.CharField(_("Complemento"), max_length=20)
    address_district = models.CharField(_("Bairro"), max_length=50)
    address_city = models.CharField(_("Cidade"), max_length=70)
    address_state = models.CharField(_("UF"), max_length=2)

    class Meta:
        """Meta definition for Teacher."""

        verbose_name = 'Professor'
        verbose_name_plural = 'Professores'

    def full_name(self):
        return f'{self.first_name.upper()} {self.last_name.upper()}'

    def __str__(self):
        """Unicode representation of Teacher."""
        return self.first_name

    def get_fields(self):
        return [(field.verbose_name, field.value_from_object(self))
                for field in self.__class__._meta.fields[1:]
                ]
>>>>>>> ee2e9db (add, configurate and edit app teacher)

templates/parciais/_navbar.html
{% load static humanize %}

<nav class="navbar navbar-expand-lg navbar-blue bg-info p-3" aria-label="Offcanvas navbar large">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">{{ school.fantasy }}</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#ofcNavbar01" aria-controls="ofcNavbar01" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end text-bg-info" tabindex="-1" id="ofcNavbar01" aria-labelledby="offcanvasNavbar2Label">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="ofcNavbar01Label"> <p> {{ school.fantasy }} </p> </h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
                <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
                    </li>
                    
                    
            {% if user.is_authenticated %}
                        
                    
                                                
                    {% if perms.school.view_school %}
                        <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Agenda
                                </a>
                                <ul class="dropdown-menu">
                                    {% if perms.calendarevent.add_calendarevent %}

                                        <li><a class="dropdown-item" href="{% url 'event_all' %}">Lista de Compromissos</a></li>
                                        <li><hr class="dropdown-divider"></li>
                                    {% endif %}
                                    <li><a class="dropdown-item" href="{% url 'day_events' %}">por Dia</a></li>
                                    <li><a class="dropdown-item" href="{% url 'week_events' %}">por Semana</a></li>
                                    <li><a class="dropdown-item" href="{% url 'scheduling' %}">por Mês</a></li>
                                </ul>
                            </li>
                    {% endif %}

                    {% if perms.school.view_school %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Escola
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'school_all' %}">Informações Cadastrais</a></li>
                                <li><a class="dropdown-item" href="{% url 'struct_all' %}">Estrutura Escular</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{% url 'discipline_all' %}">Disciplinas</a></li>
                                <li><a class="dropdown-item" href="{% url 'graduation_all' %}">Graduações</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{% url 'group_all' %}">Turmas</a></li>
                            </ul>
                        </li>  
                    {% endif %}
                    
                
                    {% if perms.teacher.view_teacher %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'teacher_all' %}">Professores</a>
                        </li>    
                    {% endif %}
                    
                    {% if perms.student.view_student %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'student_all' %}">Alunos</a>
                        </li>
                    {% endif %}

                    <li class="nav-item">
                        <a class="nav-link" href="#">Grade Escolar</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {% if user.first_name %}
                                {{ user.first_name }}
                            {% else %}
                                Usuário
                            {% endif %}
                        </a>
                        <ul class="dropdown-menu"> 
                            <li><a class="dropdown-item" href="{% url 'account_logout' %}">Sair</a></li>
                        </ul>
                    </li>
            {% endif %}
                </ul>
            </div>
        </div>
    </div>
</nav>